version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      # ↙️  aponte para o Postgres fora do compose
      # Mac / Windows:
      #   host.docker.internal resolve para o host
      # Linux (Docker ≥20.10):
      #   use host.docker.internal OU 172.17.0.1
      DATABASE_URL: postgres://postgres:password@host.docker.internal:5432/iesb_saude_api_production
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      SECRET_KEY_BASE: 2c971a3ca6a910932703ff28b8e8006313d641e00c8cd0199b68f5fd5d846ee21fc7943f98fddf3ea4b5c4b55d6f1fba629950cbe74f8c4d0d71e19710e7385d
    volumes:
      - .:/rails
    # depende apenas do próprio banco externo, então remova:
    # depends_on:
    #   - db
    command: ["bin/rails", "server", "-b", "0.0.0.0"]

# 🔥  REMOVIDO o serviço db
#volumes:
#  postgres_data:
